default:

    pastas:
        logica:
            origem: D:\\Publish\\siout\\bin
            destino: D:\\Fake\\pre-pra\\Logica  

        interface:
            origem: D:\\workspace\\SIOUT\\Interface\\dist
            destino: D:\\Fake\\pre-pra\\Interface

        documentos:
            origem: D:\\workspace\\SIOUT\\Interface\\dist
            destino: D:\\Fake\\pre-pra\\Documentos
    
    log: D:\\Fake\\pre-pra\\deploy.log